### ISSUE TITLE
Why consider rewriting using Golang?

### ISSUE THREAD

**Issue by thejoven** [Zaydo123/Solana-RPC-Listener#7]

**Comment by Zaydo123** [comment]
Hey, I decided to rewrite the token-data-processor module in golang mostly due to the faster runtimes. I plan on scaling this application to track up to a hundred or more concurrent token pairs which would be just slightly slower in python. Since python lacks true parallelism, I've opted with Go which supports both concurrent and parallel threading in order to futureproof this application. Thanks for the question 😄
